//! Typst compilation via `typst-as-lib`.
//!
//! Assembles all files needed for compilation into a temporary directory,
//! generates the `content.typ` file from converted markdown, invokes the
//! Typst compiler, and produces a PDF.
//!
//! All functions are module-level (no struct needed -- compilation is stateless).
//!
//! # Compilation pipeline
//! ```text
//! temp_dir/
//!   template.typ   <-- copied from template directory
//!   brand.typ      <-- copied from brand directory
//!   content.typ    <-- generated from Document (metadata + content sections)
//!   (assets/)      <-- any additional template/brand files
//! ```
//!
//! The Typst engine resolves `#import` paths relative to `template.typ`,
//! so all files must be co-located in the temp dir.

use std::path::Path;

use crate::domain::{Brand, ContentSections, Document, Metadata, Template};

/// Compile a document to PDF using the specified template and brand.
///
/// Steps:
/// 1. Create a temporary directory
/// 2. Copy template.typ and brand.typ into it
/// 3. Copy any additional template/brand assets
/// 4. Generate content.typ from the document's metadata and content sections
/// 5. Build a TypstEngine with file system resolver and font discovery
/// 6. Compile to a PagedDocument
/// 7. Generate PDF bytes via typst_pdf
/// 8. Write PDF to the output path
pub fn compile(
    _document: &Document,
    _template: &Template,
    _brand: &Brand,
    _output_path: &Path,
) -> anyhow::Result<()> {
    todo!("Orchestrate the full compilation pipeline")
}

/// Create a temporary directory and populate it with template, brand, and content files.
///
/// Returns the path to the temp directory (kept alive by the TempDir handle).
fn assemble_temp_dir(
    _template: &Template,
    _brand: &Brand,
    _document: &Document,
) -> anyhow::Result<tempfile::TempDir> {
    todo!("Create tempdir, copy template.typ + brand.typ + assets, write content.typ")
}

/// Generate the `content.typ` file content from document metadata and sections.
///
/// Produces the format:
/// ```typ
/// // Auto-generated by md-docs. Do not edit.
///
/// #let metadata = (
///   title: "...",
///   author: "...",
///   date: "...",
/// )
///
/// #let header = [
///   ...
/// ]
///
/// #let body = [
///   ...
/// ]
///
/// #let content = [
///   ...
/// ]
/// ```
fn generate_content_typ(_metadata: &Metadata, _sections: &ContentSections) -> String {
    todo!("Format metadata dict and content sections into valid Typst source")
}

/// Copy all files from a template directory into the temp dir.
///
/// Copies template.typ and any supplementary files (assets, images).
fn copy_template_files(_template: &Template, _temp_dir: &Path) -> anyhow::Result<()> {
    todo!("Copy template.typ and any asset files to temp_dir")
}

/// Copy brand files into the temp dir.
///
/// Copies brand.typ and any bundled font files.
fn copy_brand_files(_brand: &Brand, _temp_dir: &Path) -> anyhow::Result<()> {
    todo!("Copy brand.typ and fonts/ directory if present to temp_dir")
}

/// Invoke the Typst compiler on the assembled temp directory.
///
/// Uses `typst-as-lib`:
/// 1. Read template.typ as the main file
/// 2. Configure file system resolver for the temp dir
/// 3. Enable font discovery via typst-kit-fonts
/// 4. Compile to a PagedDocument
/// 5. Generate PDF bytes
fn compile_typst(_temp_dir: &Path) -> anyhow::Result<Vec<u8>> {
    todo!("Build TypstEngine, compile, generate PDF bytes via typst_pdf::pdf()")
}
