//! Typst compilation via `typst-as-lib`.
//!
//! Assembles all files needed for compilation into a temporary directory,
//! generates the `content.typ` file from converted markdown, invokes the
//! Typst compiler, and produces a PDF.
//!
//! All functions are module-level (no struct needed -- compilation is stateless).
//!
//! # Compilation pipeline
//! ```text
//! temp_dir/
//!   template.typ   <-- copied from template directory
//!   brand.typ      <-- copied from brand directory
//!   content.typ    <-- generated from Document (metadata + content sections)
//!   (assets/)      <-- any additional template/brand files
//! ```
//!
//! The Typst engine resolves `#import` paths relative to `template.typ`,
//! so all files must be co-located in the temp dir.

use std::path::Path;

use typst::layout::PagedDocument;
use typst_as_lib::TypstEngine;
use typst_as_lib::typst_kit_options::TypstKitFontOptions;

use crate::domain::{Brand, ContentSections, Document, Metadata, Template};

/// Compile a document to PDF using the specified template and brand.
///
/// Steps:
/// 1. Create a temporary directory
/// 2. Copy template.typ and brand.typ into it
/// 3. Copy any additional template/brand assets
/// 4. Generate content.typ from the document's metadata and content sections
/// 5. Build a TypstEngine with file system resolver and font discovery
/// 6. Compile to a PagedDocument
/// 7. Generate PDF bytes via typst_pdf
/// 8. Write PDF to the output path
pub fn compile(
    document: &Document,
    template: &Template,
    brand: &Brand,
    output_path: &Path,
) -> anyhow::Result<()> {
    let temp_dir = assemble_temp_dir(template, brand, document)?;
    let pdf_bytes = compile_typst(temp_dir.path())?;

    // Ensure parent directory exists
    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    std::fs::write(output_path, pdf_bytes)?;

    Ok(())
}

/// Create a temporary directory and populate it with template, brand, and content files.
///
/// Returns the TempDir handle (keeps the directory alive until dropped).
fn assemble_temp_dir(
    template: &Template,
    brand: &Brand,
    document: &Document,
) -> anyhow::Result<tempfile::TempDir> {
    let temp_dir = tempfile::tempdir()?;

    // Copy template files (template.typ and any assets)
    copy_template_files(template, temp_dir.path())?;

    // Copy brand files (brand.typ and any fonts)
    copy_brand_files(brand, temp_dir.path())?;

    // Generate and write content.typ
    let content_typ = generate_content_typ(&document.metadata, &document.sections);
    std::fs::write(temp_dir.path().join("content.typ"), content_typ)?;

    Ok(temp_dir)
}

/// Generate the `content.typ` file content from document metadata and sections.
///
/// Produces the format:
/// ```typ
/// // Auto-generated by md-docs. Do not edit.
///
/// #let metadata = (
///   title: "...",
///   author: "...",
///   date: "...",
/// )
///
/// #let header = [
///   ...
/// ]
///
/// #let body = [
///   ...
/// ]
///
/// #let content = [
///   ...
/// ]
/// ```
fn generate_content_typ(metadata: &Metadata, sections: &ContentSections) -> String {
    let mut output = String::new();

    output.push_str("// Auto-generated by md-docs. Do not edit.\n\n");

    // Build metadata dict
    output.push_str("#let metadata = (\n");
    output.push_str(&format!(
        "  title: \"{}\",\n",
        escape_typst_string(metadata.title.as_deref().unwrap_or(""))
    ));
    output.push_str(&format!(
        "  author: \"{}\",\n",
        escape_typst_string(metadata.author.as_deref().unwrap_or(""))
    ));
    output.push_str(&format!(
        "  date: \"{}\",\n",
        escape_typst_string(metadata.date.as_deref().unwrap_or(""))
    ));

    // Include extra metadata fields
    for (key, value) in &metadata.extra {
        let value_str = format_yml_value_for_typst(value);
        output.push_str(&format!("  {}: {},\n", key, value_str));
    }

    output.push_str(")\n\n");

    // Header section
    output.push_str("#let header = [\n");
    if !sections.header.is_empty() {
        output.push_str(&sections.header);
        output.push('\n');
    }
    output.push_str("]\n\n");

    // Body section
    output.push_str("#let body = [\n");
    if !sections.body.is_empty() {
        output.push_str(&sections.body);
        output.push('\n');
    }
    output.push_str("]\n\n");

    // Body columns array
    output.push_str("#let body-columns = (\n");
    for column in &sections.body_columns {
        output.push_str("  [\n");
        if !column.is_empty() {
            output.push_str("    ");
            output.push_str(column);
            output.push('\n');
        }
        output.push_str("  ],\n");
    }
    output.push_str(")\n\n");

    // Full content section
    output.push_str("#let content = [\n");
    if !sections.content.is_empty() {
        output.push_str(&sections.content);
        output.push('\n');
    }
    output.push_str("]\n");

    output
}

/// Copy all files from a template directory into the temp dir.
///
/// Copies template.typ and any supplementary files (assets, images).
fn copy_template_files(template: &Template, temp_dir: &Path) -> anyhow::Result<()> {
    for entry in std::fs::read_dir(&template.path)? {
        let entry = entry?;
        let src_path = entry.path();
        let file_name = entry.file_name();

        // Skip metadata.toml (not needed by Typst)
        if file_name == "metadata.toml" {
            continue;
        }

        let dst_path = temp_dir.join(&file_name);

        if src_path.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else {
            std::fs::copy(&src_path, &dst_path)?;
        }
    }

    Ok(())
}

/// Copy brand files into the temp dir.
///
/// Copies brand.typ and any bundled font files.
fn copy_brand_files(brand: &Brand, temp_dir: &Path) -> anyhow::Result<()> {
    for entry in std::fs::read_dir(&brand.path)? {
        let entry = entry?;
        let src_path = entry.path();
        let file_name = entry.file_name();

        // Skip metadata.toml (not needed by Typst)
        if file_name == "metadata.toml" {
            continue;
        }

        let dst_path = temp_dir.join(&file_name);

        if src_path.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else {
            std::fs::copy(&src_path, &dst_path)?;
        }
    }

    Ok(())
}

/// Invoke the Typst compiler on the assembled temp directory.
///
/// Uses `typst-as-lib`:
/// 1. Read template.typ as the main file
/// 2. Configure file system resolver for the temp dir
/// 3. Enable font discovery via typst-kit-fonts
/// 4. Compile to a PagedDocument
/// 5. Generate PDF bytes
fn compile_typst(temp_dir: &Path) -> anyhow::Result<Vec<u8>> {
    // Read template.typ content
    let template_content = std::fs::read_to_string(temp_dir.join("template.typ"))?;

    // Build engine with file system resolver and font discovery
    // CRITICAL: Must use search_fonts_with(TypstKitFontOptions::default()) to load
    // embedded fonts. Without this, text renders invisibly.
    let engine = TypstEngine::builder()
        .main_file(template_content)
        .with_file_system_resolver(temp_dir)
        .search_fonts_with(
            TypstKitFontOptions::default()
                .include_system_fonts(true)
                .include_embedded_fonts(true),
        )
        .build();

    // Compile the template
    let result = engine.compile::<PagedDocument>();

    // Check warnings
    for warning in &result.warnings {
        eprintln!("typst warning: {:?}", warning);
    }

    // Extract the compiled document
    let doc = result
        .output
        .map_err(|e| anyhow::anyhow!("Typst compilation failed: {:?}", e))?;

    // Generate PDF bytes
    let pdf_bytes = typst_pdf::pdf(&doc, &typst_pdf::PdfOptions::default())
        .map_err(|e| anyhow::anyhow!("PDF generation failed: {:?}", e))?;

    Ok(pdf_bytes)
}

/// Escape special characters in a string value for Typst string literals.
///
/// In Typst string literals (inside `"..."`), `"` and `\` need escaping.
fn escape_typst_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Format a serde_yml::Value for inclusion in Typst source code.
fn format_yml_value_for_typst(value: &serde_yml::Value) -> String {
    match value {
        serde_yml::Value::String(s) => format!("\"{}\"", escape_typst_string(s)),
        serde_yml::Value::Number(n) => n.to_string(),
        serde_yml::Value::Bool(b) => b.to_string(),
        serde_yml::Value::Sequence(seq) => {
            let items: Vec<String> = seq.iter().map(format_yml_value_for_typst).collect();
            format!("({})", items.join(", "))
        }
        serde_yml::Value::Null => "none".to_string(),
        _ => format!("\"{}\"", escape_typst_string(&format!("{:?}", value))),
    }
}

/// Recursively copy a directory.
fn copy_dir_recursive(src: &Path, dst: &Path) -> anyhow::Result<()> {
    std::fs::create_dir_all(dst)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());
        if src_path.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else {
            std::fs::copy(&src_path, &dst_path)?;
        }
    }
    Ok(())
}
