//! Typst compilation: temp dir assembly, content.typ generation, PDF output.

use std::path::Path;

use typst::layout::PagedDocument;
use typst_as_lib::TypstEngine;
use typst_as_lib::typst_kit_options::TypstKitFontOptions;

use crate::domain::{Brand, ContentSections, Document, Metadata, Template};

// Embedded fallback fonts (SIL OFL 1.1)
static EB_GARAMOND_REGULAR: &[u8] = include_bytes!("../../assets/EBGaramond-Regular.ttf");
static EB_GARAMOND_BOLD: &[u8] = include_bytes!("../../assets/EBGaramond-Bold.ttf");
static EB_GARAMOND_ITALIC: &[u8] = include_bytes!("../../assets/EBGaramond-Italic.ttf");
static INTER_REGULAR: &[u8] = include_bytes!("../../assets/Inter_28pt-Regular.ttf");
static INTER_BOLD: &[u8] = include_bytes!("../../assets/Inter_28pt-Bold.ttf");
static INTER_ITALIC: &[u8] = include_bytes!("../../assets/Inter_28pt-Italic.ttf");
static INTER_LIGHT: &[u8] = include_bytes!("../../assets/Inter_28pt-Light.ttf");
static IBM_PLEX_MONO_LIGHT: &[u8] = include_bytes!("../../assets/IBMPlexMono-Light.ttf");

/// Result of a successful Typst compilation.
#[derive(Debug)]
pub struct CompileResult {
    pub warnings: Vec<String>,
}

/// Compile a document to PDF using the specified template and brand.
pub fn compile(
    document: &Document,
    template: &Template,
    brand: &Brand,
    output_path: &Path,
) -> anyhow::Result<CompileResult> {
    let temp_dir = assemble_temp_dir(template, brand, document)?;
    let (pdf_bytes, warnings) = compile_typst(temp_dir.path())?;

    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    std::fs::write(output_path, pdf_bytes)?;

    Ok(CompileResult { warnings })
}

/// Create a temp dir populated with template, brand, and content files.
fn assemble_temp_dir(
    template: &Template,
    brand: &Brand,
    document: &Document,
) -> anyhow::Result<tempfile::TempDir> {
    let temp_dir = tempfile::tempdir()?;

    copy_dir_files(&template.path, temp_dir.path())?;
    copy_dir_files(&brand.path, temp_dir.path())?;

    let content_typ = generate_content_typ(&document.metadata, &document.sections);
    std::fs::write(temp_dir.path().join("content.typ"), content_typ)?;

    Ok(temp_dir)
}

/// Generate the `content.typ` source from document metadata and sections.
fn generate_content_typ(metadata: &Metadata, sections: &ContentSections) -> String {
    let mut output = String::new();

    output.push_str("// Auto-generated by md-docs. Do not edit.\n\n");

    output.push_str("#let metadata = (\n");
    output.push_str(&format!(
        "  title: \"{}\",\n",
        escape_typst_string(metadata.title.as_deref().unwrap_or(""))
    ));
    output.push_str(&format!(
        "  author: \"{}\",\n",
        escape_typst_string(metadata.author.as_deref().unwrap_or(""))
    ));
    output.push_str(&format!(
        "  date: \"{}\",\n",
        escape_typst_string(metadata.date.as_deref().unwrap_or(""))
    ));

    for (key, value) in &metadata.extra {
        let value_str = format_yml_value_for_typst(value);
        output.push_str(&format!("  {}: {},\n", key, value_str));
    }

    output.push_str(")\n\n");

    output.push_str("#let header = [\n");
    if !sections.header.is_empty() {
        output.push_str(&sections.header);
        output.push('\n');
    }
    output.push_str("]\n\n");

    output.push_str("#let body = [\n");
    if !sections.body.is_empty() {
        output.push_str(&sections.body);
        output.push('\n');
    }
    output.push_str("]\n\n");

    output.push_str("#let body-columns = (\n");
    for column in &sections.body_columns {
        output.push_str("  [\n");
        if !column.is_empty() {
            output.push_str("    ");
            output.push_str(column);
            output.push('\n');
        }
        output.push_str("  ],\n");
    }
    output.push_str(")\n\n");

    output.push_str("#let content = [\n");
    if !sections.content.is_empty() {
        output.push_str(&sections.content);
        output.push('\n');
    }
    output.push_str("]\n");

    output
}

/// Copy files from a source directory into the temp dir, skipping metadata.toml.
fn copy_dir_files(src: &Path, dst: &Path) -> anyhow::Result<()> {
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let file_name = entry.file_name();
        if file_name == "metadata.toml" {
            continue;
        }
        let src_path = entry.path();
        let dst_path = dst.join(&file_name);
        if src_path.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else {
            std::fs::copy(&src_path, &dst_path)?;
        }
    }
    Ok(())
}

/// Invoke the Typst compiler on the assembled temp directory.
fn compile_typst(temp_dir: &Path) -> anyhow::Result<(Vec<u8>, Vec<String>)> {
    let template_content = std::fs::read_to_string(temp_dir.join("template.typ"))?;

    // Custom fonts registered first via .fonts(), then system fonts merged via search_fonts_with
    let engine = TypstEngine::builder()
        .main_file(template_content)
        .with_file_system_resolver(temp_dir)
        .fonts([
            EB_GARAMOND_REGULAR,
            EB_GARAMOND_BOLD,
            EB_GARAMOND_ITALIC,
            INTER_REGULAR,
            INTER_BOLD,
            INTER_ITALIC,
            INTER_LIGHT,
            IBM_PLEX_MONO_LIGHT,
        ])
        .search_fonts_with(
            TypstKitFontOptions::default()
                .include_system_fonts(true),
        )
        .build();

    let result = engine.compile::<PagedDocument>();
    let warnings: Vec<String> = result.warnings.iter().map(|w| format!("{:?}", w)).collect();

    let doc = result
        .output
        .map_err(|e| anyhow::anyhow!("Typst compilation failed: {:?}", e))?;

    let pdf_bytes = typst_pdf::pdf(&doc, &typst_pdf::PdfOptions::default())
        .map_err(|e| anyhow::anyhow!("PDF generation failed: {:?}", e))?;

    Ok((pdf_bytes, warnings))
}

/// Escape special characters for Typst string literals.
fn escape_typst_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Format a serde_yml::Value for inclusion in Typst source code.
fn format_yml_value_for_typst(value: &serde_yml::Value) -> String {
    match value {
        serde_yml::Value::String(s) => format!("\"{}\"", escape_typst_string(s)),
        serde_yml::Value::Number(n) => n.to_string(),
        serde_yml::Value::Bool(b) => b.to_string(),
        serde_yml::Value::Sequence(seq) => {
            let items: Vec<String> = seq.iter().map(format_yml_value_for_typst).collect();
            format!("({})", items.join(", "))
        }
        serde_yml::Value::Null => "none".to_string(),
        _ => format!("\"{}\"", escape_typst_string(&format!("{:?}", value))),
    }
}

/// Recursively copy a directory.
fn copy_dir_recursive(src: &Path, dst: &Path) -> anyhow::Result<()> {
    std::fs::create_dir_all(dst)?;
    for entry in std::fs::read_dir(src)? {
        let entry = entry?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());
        if src_path.is_dir() {
            copy_dir_recursive(&src_path, &dst_path)?;
        } else {
            std::fs::copy(&src_path, &dst_path)?;
        }
    }
    Ok(())
}
